dist: bionic
sudo: false
language: cpp

git:
    submodules: false
addons:
    apt:
        packages:
            - libyaml-cpp-dev

script:
    - mkdir build
    - cd build
    - cmake .. -DSABLE_BUILD_TESTS=ON
    - make
    - ctest
