os: linux
dist: bionic
language: cpp

git:
    submodules: false

script:
    - mkdir -p build
    - cd build
    - cmake .. -DSABLE_BUILD_TESTS=ON -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . -- -j2
    - ctest -j2 -V
    
after_success:
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
